language: groovy

jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

sudo: required
services:
  - docker

before_install:
  - docker pull thomsonreuters/transmart-postgres
  - docker run -d -p 5433:5432 --name transmart-postgres thomsonreuters/transmart-postgres
  - while ! PGPASSWORD=postgres psql --host 127.0.0.1 -p 5433 -U postgres -c "SELECT 1;"; do sleep 5; done

before_script:
  - echo -e "db { jdbcDriver = 'org.postgresql.Driver'; jdbcConnectionString = 'jdbc:postgresql://127.0.0.1:5433/transmart'; username = 'postgres'; password = 'postgres' }" > src/test/resources/TestConfig.groovy
  - gradle runSqlScripts -Pconfig=src/test/resources/TestConfig.groovy -Pdba-user=postgres -Pdba-password=postgres
