SET SERVEROUTPUT ON SIZE UNLIMITED
SET HEAD OFF
SET LINESIZE 180

SELECT '20160805133000000_ADD_COLUMN.sql'
FROM DUAL;

DECLARE
  cnt INT;
BEGIN
  SELECT count(*)
  INTO cnt
  FROM dba_tab_cols c
  WHERE c.table_name = 'LT_SRC_CLINICAL_DATA' AND c.column_name = 'START_DATE' and owner = 'TM_DATALOADER';
  IF (cnt <> 1)
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TM_DATALOADER.LT_SRC_CLINICAL_DATA ADD (START_DATE VARCHAR2 (250) )';
  END IF;

  SELECT count(*)
  INTO cnt
  FROM dba_tab_cols c
  WHERE c.table_name = 'LT_SRC_CLINICAL_DATA' AND c.column_name = 'INSTANCE_NUM' and owner = 'TM_DATALOADER';
  IF (cnt <> 1)
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TM_DATALOADER.LT_SRC_CLINICAL_DATA ADD (INSTANCE_NUM VARCHAR2 (250) )';
  END IF;

  SELECT count(*)
  INTO cnt
  FROM dba_tab_cols c
  WHERE c.table_name = 'LT_SRC_CLINICAL_DATA' AND c.column_name = 'TRIAL_VISIT_LABEL' and owner = 'TM_DATALOADER';
  IF (cnt <> 1)
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TM_DATALOADER.LT_SRC_CLINICAL_DATA ADD (TRIAL_VISIT_LABEL VARCHAR2 (900) )';
  END IF;

  SELECT count(*)
  INTO cnt
  FROM dba_tab_cols c
  WHERE c.table_name = 'LT_SRC_CLINICAL_DATA' AND c.column_name = 'TRIAL_VISIT_UNIT' and owner = 'TM_DATALOADER';
  IF (cnt <> 1)
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TM_DATALOADER.LT_SRC_CLINICAL_DATA ADD (TRIAL_VISIT_UNIT VARCHAR2 (250) )';
  END IF;

  SELECT count(*)
  INTO cnt
  FROM dba_tab_cols c
  WHERE c.table_name = 'LT_SRC_CLINICAL_DATA' AND c.column_name = 'TRIAL_VISIT_TIME' and owner = 'TM_DATALOADER';
  IF (cnt <> 1)
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TM_DATALOADER.LT_SRC_CLINICAL_DATA ADD (TRIAL_VISIT_TIME VARCHAR2 (250) )';
  END IF;

  SELECT count(*)
  INTO cnt
  FROM dba_tab_cols c
  WHERE c.table_name = 'LT_SRC_CLINICAL_DATA' AND c.column_name = 'CONCEPT_CD' and owner = 'TM_DATALOADER';
  IF (cnt <> 1)
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TM_DATALOADER.LT_SRC_CLINICAL_DATA ADD (CONCEPT_CD VARCHAR2 (250) )';
  END IF;

  SELECT count(*)
  INTO cnt
  FROM dba_tab_cols c
  WHERE c.table_name = 'WRK_CLINICAL_DATA' AND c.column_name = 'START_DATE' and owner = 'TM_DATALOADER';
  IF (cnt <> 1)
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TM_DATALOADER.WRK_CLINICAL_DATA ADD (START_DATE VARCHAR2 (250) )';
  END IF;

  SELECT count(*)
  INTO cnt
  FROM dba_tab_cols c
  WHERE c.table_name = 'WRK_CLINICAL_DATA' AND c.column_name = 'INSTANCE_NUM' and owner = 'TM_DATALOADER';
  IF (cnt <> 1)
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TM_DATALOADER.WRK_CLINICAL_DATA ADD (INSTANCE_NUM VARCHAR2 (250) )';
  END IF;

  SELECT count(*)
  INTO cnt
  FROM dba_tab_cols c
  WHERE c.table_name = 'WRK_CLINICAL_DATA' AND c.column_name = 'TRIAL_VISIT_LABEL' and owner = 'TM_DATALOADER';
  IF (cnt <> 1)
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TM_DATALOADER.WRK_CLINICAL_DATA ADD (TRIAL_VISIT_LABEL VARCHAR2 (900) )';
  END IF;

  SELECT count(*)
  INTO cnt
  FROM dba_tab_cols c
  WHERE c.table_name = 'WRK_CLINICAL_DATA' AND c.column_name = 'TRIAL_VISIT_TIME' and owner = 'TM_DATALOADER';
  IF (cnt <> 1)
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TM_DATALOADER.WRK_CLINICAL_DATA ADD (TRIAL_VISIT_TIME VARCHAR2 (250) )';
  END IF;

  SELECT count(*)
  INTO cnt
  FROM dba_tab_cols c
  WHERE c.table_name = 'WRK_CLINICAL_DATA' AND c.column_name = 'TRIAL_VISIT_UNIT' and owner = 'TM_DATALOADER';
  IF (cnt <> 1)
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TM_DATALOADER.WRK_CLINICAL_DATA ADD (TRIAL_VISIT_UNIT VARCHAR2 (250) )';
  END IF;

  SELECT count(*)
  INTO cnt
  FROM dba_tab_cols c
  WHERE c.table_name = 'WRK_CLINICAL_DATA' AND c.column_name = 'CONCEPT_CD' and owner = 'TM_DATALOADER';
  IF (cnt <> 1)
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TM_DATALOADER.WRK_CLINICAL_DATA ADD (CONCEPT_CD VARCHAR2 (250) )';
  END IF;

  SELECT count(*)
  INTO cnt
  FROM dba_tab_cols c
  WHERE c.table_name = 'WT_TRIAL_NODES' AND c.column_name = 'CONCEPT_CD' and owner = 'TM_DATALOADER';
  IF (cnt <> 1)
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TM_DATALOADER.WT_TRIAL_NODES ADD (CONCEPT_CD VARCHAR2 (250) )';
  END IF;


  EXECUTE IMMEDIATE 'CREATE TABLE tm_dataloader.concept_specific_trials
			(
				trial_visit_num NUMBER (38, 0),
				c_fullname VARCHAR2 (700)
			)
			';
END;

/