SET SERVEROUTPUT ON SIZE UNLIMITED
SET HEAD OFF
SET LINESIZE 180

SELECT '20160805133000000_ADD_COLUMN_FOR_TIMESTAMP.sql'
FROM DUAL;

DECLARE
  cnt INT;
BEGIN
  SELECT count(*)
  INTO cnt
  FROM dba_tab_cols c
  WHERE c.table_name = 'LT_SRC_CLINICAL_DATA' AND c.column_name = 'START_DATE' and owner = 'TM_DATALOADER';
  IF (cnt <> 1)
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TM_DATALOADER.LT_SRC_CLINICAL_DATA ADD (START_DATE VARCHAR2 (250) )';
  END IF;

  SELECT count(*)
  INTO cnt
  FROM dba_tab_cols c
  WHERE c.table_name = 'LT_SRC_CLINICAL_DATA' AND c.column_name = 'INSTANCE_NUM' and owner = 'TM_DATALOADER';
  IF (cnt <> 1)
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TM_DATALOADER.LT_SRC_CLINICAL_DATA ADD (INSTANCE_NUM VARCHAR2 (250) )';
  END IF;

  SELECT count(*)
  INTO cnt
  FROM dba_tab_cols c
  WHERE c.table_name = 'WRK_CLINICAL_DATA' AND c.column_name = 'START_DATE' and owner = 'TM_DATALOADER';
  IF (cnt <> 1)
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TM_DATALOADER.WRK_CLINICAL_DATA ADD (START_DATE VARCHAR2 (250) )';
  END IF;

  SELECT count(*)
  INTO cnt
  FROM dba_tab_cols c
  WHERE c.table_name = 'WRK_CLINICAL_DATA' AND c.column_name = 'INSTANCE_NUM' and owner = 'TM_DATALOADER';
  IF (cnt <> 1)
  THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TM_DATALOADER.WRK_CLINICAL_DATA ADD (INSTANCE_NUM VARCHAR2 (250) )';
  END IF;

END;

/