set define on;

DEFINE TM_LZ_SCHEMA='TM_LZ';

DROP TABLE "&TM_LZ_SCHEMA".LT_SRC_MRNA_XML_DATA;

CREATE TABLE "&TM_LZ_SCHEMA".LT_SRC_MRNA_XML_DATA (
    STUDY_ID varchar2(50) NOT NULL,
    CATEGORY_CD varchar2(2000) NOT NULL,
    C_METADATAXML varchar2(3000) NOT NULL
);