SET DEFINE ON;

DEFINE TM_CZ_SCHEMA='TM_CZ';

DECLARE
  flag NUMBER(1, 0);
BEGIN
  SELECT COUNT(*)
  INTO flag
  FROM dba_tables
  WHERE table_name = 'LT_SRC_GWAS_DATA';

  IF flag <> 0
  THEN
    RETURN;
  END IF;

  EXECUTE IMMEDIATE 'CREATE TABLE TM_CZ.LT_SRC_GWAS_DATA
  (
    study_id    CHARACTER VARYING(25),
    subject_id  CHARACTER VARYING(30),
    category_cd CHARACTER VARYING(250),
    data_label  CHARACTER VARYING(500)
  )';

END;
/

GRANT INSERT, UPDATE, DELETE, SELECT ON TM_CZ.LT_SRC_GWAS_DATA TO TM_CZ;
GRANT SELECT ON TM_CZ.LT_SRC_GWAS_DATA TO biomart_user;
/