
DROP INDEX "I2B2DEMODATA"."OF_CTX_BLOB";



CREATE INDEX "TM_WZ"."IDX_WTN_LOAD_CLINICAL" ON "TM_WZ"."WT_TRIAL_NODES"
  (
    "LEAF_NODE",
    "CATEGORY_CD",
    "DATA_LABEL"
  );
  
  
  
  CREATE INDEX "I2B2DEMODATA"."IDX_PD_SOURCESYSTEMCD_PNUM" ON "I2B2DEMODATA"."PATIENT_DIMENSION"
  (
    "SOURCESYSTEM_CD",
    "PATIENT_NUM"
  );
  
  
  CREATE INDEX "TM_CZ"."IDX_TMP_SUBJ_USUBJID" ON "TM_CZ"."TMP_SUBJECT_INFO"
  (
    "USUBJID"
  );
  
  CREATE INDEX "TM_LZ"."IDX_SCD_STUDY" ON "TM_LZ"."LT_SRC_CLINICAL_DATA"
  (
    "STUDY_ID"
  );
  
  
CREATE INDEX CZ_JOB_AUDIT_JOBID_DATE ON TM_CZ.CZ_JOB_AUDIT (JOB_ID, JOB_DATE);
CREATE INDEX IX_DE_SUBJECT_SMPL_MPNG_MRNA ON DEAPP.DE_SUBJECT_SAMPLE_MAPPING (TRIAL_NAME, PLATFORM, SOURCE_CD, CONCEPT_CODE);
CREATE INDEX IX_I2B2_SOURCE_SYSTEM_CD ON I2B2METADATA.I2B2 (SOURCESYSTEM_CD);

ALTER TABLE "TM_WZ"."WRK_CLINICAL_DATA" CACHE;
ALTER TABLE "TM_WZ"."WRK_CLINICAL_DATA" NOLOGGING;

ALTER TABLE "TM_LZ"."LT_SRC_CLINICAL_DATA" CACHE;
ALTER TABLE "TM_LZ"."LT_SRC_CLINICAL_DATA" NOLOGGING;

CREATE INDEX IDX_CCONCEPT_PATH ON i2b2demodata.CONCEPT_COUNTS (CONCEPT_PATH);

CREATE INDEX IDX_I2B2_SECURE_FULLNAME ON I2B2METADATA.I2B2_SECURE (C_FULLNAME);

CREATE INDEX "I2B2METADATA"."IDX_I2B2_FULLNAME_BASECODE" ON "I2B2METADATA"."I2B2"
  (
    "C_FULLNAME",
    "C_BASECODE"
  );
  
DROP INDEX TM_WZ.IDX_WT_TRIALNODES;
CREATE INDEX "TM_WZ"."IDX_WT_TRIALNODES" ON "TM_WZ"."WT_TRIAL_NODES"
  (
    "LEAF_NODE",
    "NODE_NAME"
  )  
  
 CREATE INDEX "DEAPP"."IDX_DE_SUBJ_SMPL_TRIAL_CCODE" ON "DEAPP"."DE_SUBJECT_SAMPLE_MAPPING"
  (
    "TRIAL_NAME",
    "CONCEPT_CODE"
  );

  
  CREATE TABLE "TM_WZ"."I2B2_LOAD_PATH"
  (
    "PATH" VARCHAR2(700 BYTE),
    "RECORD_ID" ROWID,
    PRIMARY KEY ("PATH", "RECORD_ID")
  )  
  ORGANIZATION INDEX NOLOGGING;
  
  
  CREATE TABLE "TM_WZ"."I2B2_LOAD_TREE_FULL"
  (
    "IDROOT"          ROWID,
    "IDCHILD"         ROWID,
	PRIMARY KEY(IDROOT, IDCHILD)
	
  )  
  ORGANIZATION INDEX NOLOGGING;
  grant privileges on "I2B2METADATA"."I2B2_LOAD_TREE" to tm_cz;*/
  grant all privileges on "TM_WZ"."I2B2_LOAD_TREE_FULL" to tm_cz;
  grant all privileges on "TM_WZ"."I2B2_LOAD_PATH" to tm_cz;
  
---------------------------------------------

DROP TABLE TM_WZ.I2B2_LOAD_PATH_WITH_COUNT;
 
CREATE TABLE "TM_WZ"."I2B2_LOAD_PATH_WITH_COUNT"
  (
    "C_FULLNAME"          VARCHAR2(700 BYTE),
    "NBR_CHILDREN"         NUMBER,
    PRIMARY KEY(C_FULLNAME)
  )  
  ORGANIZATION INDEX NOLOGGING;
  
grant all privileges on "TM_WZ"."I2B2_LOAD_PATH_WITH_COUNT" to tm_cz;


DROP INDEX CREATE INDEX "I2B2DEMODATA"."IDX_OB_FACT_PATIENT_NUMBER";
CREATE INDEX "I2B2DEMODATA"."IDX_OB_FACT_PATIENT_NUMBER" ON "I2B2DEMODATA"."OBSERVATION_FACT" ("PATIENT_NUM", "CONCEPT_CD");

DROP INDEX "TM_CZ"."CZ_JOB_AUDIT_JOBID_DATE";
CREATE INDEX "TM_CZ"."CZ_JOB_AUDIT_JOBID_DATE" ON TM_CZ.CZ_JOB_AUDIT (JOB_ID, JOB_DATE);
DROP INDEX "DEAPP"."IX_DE_SUBJECT_SMPL_MPNG_MRNA";
CREATE INDEX "DEAPP"."IX_DE_SUBJECT_SMPL_MPNG_MRNA" ON DEAPP.DE_SUBJECT_SAMPLE_MAPPING (TRIAL_NAME, PLATFORM, SOURCE_CD, CONCEPT_CODE);
DROP INDEX "I2B2METADATA"."IX_I2B2_SOURCE_SYSTEM_CD";
CREATE INDEX "I2B2METADATA"."IX_I2B2_SOURCE_SYSTEM_CD" ON I2B2METADATA.I2B2 (SOURCESYSTEM_CD);

DROP INDEX "DEAPP"."IDX_DE_MICROARRAY_DATA_1";
CREATE INDEX "DEAPP"."IDX_DE_MICROARRAY_DATA_1" ON "DEAPP"."DE_SUBJECT_MICROARRAY_DATA" ("TRIAL_NAME", "ASSAY_ID", "PROBESET_ID") parallel nologging;
DROP INDEX "DEAPP"."IDX_DE_MICROARRAY_DATA_2";
CREATE INDEX "DEAPP"."IDX_DE_MICROARRAY_DATA_2" ON "DEAPP"."DE_SUBJECT_MICROARRAY_DATA" ("ASSAY_ID", "PROBESET_ID") parallel nologging;
DROP INDEX "DEAPP"."IDX_DE_MICROARRAY_DATA_3";
DROP INDEX "SYSTEM"."IDX_DE_MICROARRAY_DATA_3";
CREATE INDEX "DEAPP"."IDX_DE_MICROARRAY_DATA_3" ON "DEAPP"."DE_SUBJECT_MICROARRAY_DATA" ("TRIAL_SOURCE")  parallel nologging;

CREATE INDEX "TM_WZ"."IDX_WRK_CD" ON "TM_WZ"."WRK_CLINICAL_DATA" (DATA_TYPE ASC, DATA_VALUE ASC, VISIT_NAME ASC, DATA_LABEL ASC, CATEGORY_CD ASC, USUBJID ASC);