CREATE TABLE "TM_LZ"."LT_SNP_CALLS_BY_GSM" 
   (	"GSM_NUM" VARCHAR2(10 BYTE), 	
	"SNP_NAME" VARCHAR2(100 BYTE), 
	"SNP_CALLS" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "TRANSMART" ;

CREATE TABLE "TM_LZ"."LT_SNP_COPY_NUMBER"   
  (	
	"SNP_NAME" VARCHAR2(50 BYTE), 
	"CHROM" VARCHAR2(2 BYTE), 
	"CHROM_POS" NUMBER(20,0), 
	"COPY_NUMBER" NUMBER(2,0),
  "GSM_NUM" VARCHAR(10 byte)
   ) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "TRANSMART" ;
 
CREATE TABLE "TM_LZ"."LT_SNP_GENE_MAP"
  (
	"SNP_NAME" VARCHAR2(256 BYTE),
	"ENTREZ_GENE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "TRANSMART" ;