CREATE TABLE "TM_LZ"."LT_SNP_CALLS_BY_GSM" 
   (	"GSM_NUM" VARCHAR2(10 BYTE), 	
	"SNP_NAME" VARCHAR2(100 BYTE), 
	"SNP_CALLS" VARCHAR2(4 BYTE)
   )
TABLESPACE "TRANSMART" ;

CREATE TABLE "TM_LZ"."LT_SNP_COPY_NUMBER"   
  (	
	"SNP_NAME" VARCHAR2(50 BYTE), 
	"CHROM" VARCHAR2(2 BYTE), 
	"CHROM_POS" NUMBER(20,0), 
	"COPY_NUMBER" FLOAT(53),
  "GSM_NUM" VARCHAR(10 byte)
   )
TABLESPACE "TRANSMART" ;
 
CREATE TABLE "TM_LZ"."LT_SNP_GENE_MAP"
  (
	"SNP_NAME" VARCHAR2(256 BYTE),
	"ENTREZ_GENE_ID" NUMBER
   )
TABLESPACE "TRANSMART" ;