  DROP TABLE IF EXISTS TM_WZ.I2B2_LOAD_PATH;

  CREATE UNLOGGED TABLE TM_WZ.I2B2_LOAD_PATH
  (
    PATH character varying(700) PRIMARY KEY,
	PATH50 character varying(50),
	PATH100 character varying(100),
	PATH150 character varying(150),
	PATH200 character varying(200),
	PATH_LEN integer,
    RECORD_ID integer
  );



  CREATE INDEX TM_WZ_IDX_PATH_LEN ON TM_WZ.I2B2_LOAD_PATH (PATH_LEN, PATH varchar_pattern_ops, RECORD_ID);
  CREATE INDEX TM_WZ_IDX_PATH_LEN50 ON TM_WZ.I2B2_LOAD_PATH (PATH_LEN, PATH50 varchar_pattern_ops, RECORD_ID);
  CREATE INDEX TM_WZ_IDX_PATH_LEN100 ON TM_WZ.I2B2_LOAD_PATH (PATH_LEN, PATH100 varchar_pattern_ops, RECORD_ID);
  CREATE INDEX TM_WZ_IDX_PATH_LEN150 ON TM_WZ.I2B2_LOAD_PATH (PATH_LEN, PATH150 varchar_pattern_ops, RECORD_ID);
  CREATE INDEX TM_WZ_IDX_PATH_LEN200 ON TM_WZ.I2B2_LOAD_PATH (PATH_LEN, PATH200 varchar_pattern_ops, RECORD_ID);

  CREATE INDEX TM_WZ_IDX_PATH ON TM_WZ.I2B2_LOAD_PATH (PATH varchar_pattern_ops, RECORD_ID);
  CREATE INDEX TM_WZ_IDX_PATH50 ON TM_WZ.I2B2_LOAD_PATH (PATH50 varchar_pattern_ops, RECORD_ID);
  CREATE INDEX TM_WZ_IDX_PATH100 ON TM_WZ.I2B2_LOAD_PATH (PATH100 varchar_pattern_ops, RECORD_ID);
  CREATE INDEX TM_WZ_IDX_PATH150 ON TM_WZ.I2B2_LOAD_PATH (PATH150 varchar_pattern_ops, RECORD_ID);
  CREATE INDEX TM_WZ_IDX_PATH200 ON TM_WZ.I2B2_LOAD_PATH (PATH200 varchar_pattern_ops, RECORD_ID);


  DROP TABLE IF EXISTS TM_WZ.I2B2_LOAD_TREE_FULL;
  CREATE UNLOGGED TABLE TM_WZ.I2B2_LOAD_TREE_FULL
  (
    IDROOT          integer,
    IDCHILD         integer
  ) ;

  CREATE INDEX TM_WZ_IDX_ROOT ON TM_WZ.I2B2_LOAD_TREE_FULL (IDROOT, IDCHILD);
  CREATE INDEX TM_WZ_IDX_CHILD ON TM_WZ.I2B2_LOAD_TREE_FULL (IDCHILD, IDROOT);

  ALTER TABLE I2B2Metadata.i2b2 ADD COLUMN RECORD_ID SERIAL;
  CREATE INDEX I2B2META_IDX_RECORD_ID ON I2B2Metadata.i2b2 (RECORD_ID);



  CREATE UNLOGGED TABLE TM_WZ.I2B2_LOAD_PATH_WITH_COUNT
  (
    C_FULLNAME          character varying(700) PRIMARY KEY,
    NBR_CHILDREN        INTEGER
  );

  CREATE INDEX TM_WZ_IDX_PATH_COUNT ON TM_WZ.I2B2_LOAD_PATH_WITH_COUNT (C_FULLNAME);
  CREATE INDEX IDX_CCONCEPT_PATH ON i2b2demodata.CONCEPT_COUNTS (CONCEPT_PATH);
CREATE INDEX IDX_PD_SOURCESYSTEMCD_PNUM ON I2B2DEMODATA.PATIENT_DIMENSION(SOURCESYSTEM_CD, PATIENT_NUM);
CREATE INDEX IDX_WTN_LOAD_CLINICAL ON TM_WZ.WT_TRIAL_NODES(LEAF_NODE,CATEGORY_CD,DATA_LABEL);
CREATE INDEX IX_I2B2_SOURCE_SYSTEM_CD ON I2B2METADATA.I2B2 (SOURCESYSTEM_CD);
CREATE INDEX IDX_I2B2_FULLNAME_BASECODE ON I2B2METADATA.I2B2(C_FULLNAME, C_BASECODE);
CREATE INDEX IDX_I2B2_BASECODE ON I2B2METADATA.I2B2(C_BASECODE, RECORD_ID, c_visualattributes);

CREATE INDEX IDX_WT_TRIALNODES ON TM_WZ.WT_TRIAL_NODES(LEAF_NODE,NODE_NAME);
CREATE INDEX IDX_DE_SUBJ_SMPL_TRIAL_CCODE ON DEAPP.DE_SUBJECT_SAMPLE_MAPPING(TRIAL_NAME, CONCEPT_CODE);
CREATE INDEX IDX_I2B2_SECURE_FULLNAME ON I2B2METADATA.I2B2_SECURE (C_FULLNAME);

CREATE INDEX IDX_FACT_PATIENT_NUM ON I2B2DEMODATA.OBSERVATION_FACT (PATIENT_NUM);

ALTER TABLE tm_wz.wt_trial_nodes ALTER COLUMN category_cd TYPE character varying(250);
ALTER TABLE tm_wz.wt_num_data_types ALTER COLUMN category_cd TYPE character varying(250);


CREATE INDEX IDX_WRK_CLN_ID_VALUE ON TM_WZ.WRK_CLINICAL_DATA(usubjid, data_value, data_type);