\i ./median.sql
\i ./AUDIT_FUNCTIONS.sql
\i ./I2B2_ADD_NODE.sql
\i ./I2B2_CREATE_CONCEPT_COUNTS.sql
\i ./I2B2_DELETE_1_NODE.sql
\i ./I2B2_LOAD_SECURITY_DATA.sql
\i ./I2B2_LOAD_SAMPLES.sql
\i ./I2B2_PROCESS_MRNA_DATA.sql
\i ./I2B2_CREATE_FULL_TREE.sql
\i ./I2B2_LOAD_CLINICAL_DATA.sql
\i ./I2B2_PROCESS_SNP_DATA.sql
\i ./I2B2_PROCESS_VCF_DATA.sql
\i ./I2B2_DELETE_ALL_DATA.sql
\i ./I2B2_MOVE_STUDY.sql

