SET SERVEROUTPUT ON SIZE UNLIMITED
SET HEAD OFF
SET LINESIZE 180

SELECT '20161218000000000_add_platform_for_protein_tables.sql' FROM DUAL;

DECLARE
  cnt INT;
BEGIN
  SELECT count(*) INTO cnt
    FROM dba_tab_cols c
   WHERE c.table_name = 'WT_SUBJECT_PROTEOMICS_LOGS' AND c.column_name = 'PLATFORM' and owner = 'TM_DATALOADER';
  IF (cnt <> 1) THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TM_DATALOADER.WT_SUBJECT_PROTEOMICS_LOGS ADD (PLATFORM VARCHAR2(200))';
  END IF;
  SELECT count(*) INTO cnt
    FROM dba_tab_cols c
   WHERE c.table_name = 'WT_SUBJECT_PROTEOMICS_MED' AND c.column_name = 'PLATFORM' and owner = 'TM_DATALOADER';
  IF (cnt <> 1) THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TM_DATALOADER.WT_SUBJECT_PROTEOMICS_MED ADD (PLATFORM VARCHAR2(200))';
  END IF;

END;
/
