--
-- Type: TABLE; Owner: TM_DATALOADER; Name: LT_SRC_QPCR_MIRNA_DATA
--
 CREATE TABLE "TM_DATALOADER"."LT_SRC_QPCR_MIRNA_DATA" 
  (	"TRIAL_NAME" VARCHAR2(25 BYTE), 
"PROBESET" VARCHAR2(100 BYTE), 
"EXPR_ID" VARCHAR2(100 BYTE), 
"INTENSITY_VALUE" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

