--
-- Type: TABLE; Owner: TM_DATALOADER; Name: WT_DEL_NODES
--
 CREATE TABLE "TM_DATALOADER"."WT_DEL_NODES" 
  (	"C_FULLNAME" VARCHAR2(1000 BYTE), 
"C_BASECODE" VARCHAR2(500 BYTE)
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "TRANSMART" ;

